# Generated by Django 2.2.11 on 2020-03-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='班级分类')),
                ('status', models.PositiveIntegerField(choices=[(1, '显示'), (0, '不显示')], default=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '班级分类',
                'verbose_name_plural': '班级分类',
            },
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('image', models.ImageField(upload_to='images/', verbose_name='图片')),
                ('content', models.CharField(max_length=100, null=True, verbose_name='内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('category', models.ForeignKey(max_length=20, on_delete=False, to='image_app.CategoryModel', verbose_name='班级分类')),
            ],
            options={
                'verbose_name': '提交内容',
                'verbose_name_plural': '提交内容',
                'ordering': ['-created_time'],
            },
        ),
    ]
